language: java
jdk:
- oraclejdk8
script: "./gradlew build distZip --scan -s"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

addons:
  sonarcloud:
    organization: "thomasrepnik-github"
    token:
      secure: "P1runspQ0IA1Q8RVkTgWX/7CrLC/WEOpnKcv5RMRaHHPrHsck/YjHXfl/gKOp+XvNGJ4uDPEkW8vjDtOy/uSVd6SWwKp3v9xHYwWSaxJyIEbWvf/BfVjZ3UAeco3YUZaTj2oQ2RSfaZXPl0i46dpPPPHydsWnxybJN/D3w+TPulGaaTTsL7TVOc9iBNOV2wFDyclFlainx8B8zvh8WgzjCKP4LtloO+zltwDyf/6MfXLN3hvl8H34QpNTGdxcGPJ3gNKWdLk6p6RZ19fM660JQzwEX0sDNVwtCDVHse9DZFQzdldw3E56+hPbJcNJuM37FfebjnJrqK66h0DQPzmGH2XKdmPziY+q0ZdcMd7++Og9O/kss5ToiFcCfrTYhVbeAgAz4zydNcFpB1i7lgrvIRIIeRTh/MwLpU4UMUfwpcXZt4vDcGzGKYYsDEDHyWy9SygS60cIpZqHpQj4yJChjyMaIXgdParIP7de4Z0GLBZ9WwjA+srE4/TMpFBn9tQyGMHKLA7G49u5+v/3EkUXEOhaMYh2dMtgxqfnw44TRv4reqakqqs1HEDq+DSNKqTAys8Kx9kT/sOXZfGOVl//4tB8elyJ2CLU6Q1qJgjnKm201OtZ/MRTBKwkrazZAybMrSL0i5m4WxHRLKmnlmupO0wiR8cJKUYuUa2yqELQuo="
script:
  - sonar-scanner

deploy:
  provider: releases
  api_key:
    secure: zvjVodDrHe5mgL7tz+KefuUALayalVIpIqqI71UTvmkyUQFSsssKk47HgN5jPZuisYn0/jGnkRKoO6nWKs8Shz1KMgKfaY5DghUE8vaE6y37el0yWaMbvFtSWpzugGzODWXetY+4WROmr1k1rx15f3JZ1RWWwt/x3OuerKrJ5Rf6V4z8TuFW/OwMtKSYnZ0/cP5SkYoWVy+bEVRV/Lj93cWc9DfYSpRl1ub0F4rK8MG0qAZeJzzDcfzaUJfINMNuFdhR//Cv7CJiZDNlhdPK7uI4eHdXJok3ffx8+sukq50uQeIC+FhLPr9tghp5NM7jFp1pPwA5knWrch1cwrFIJalyNFKZCY2wxERr4y2KZvy/qgSyip+Ymz3qWsrHlsuuD0XqJ86/V9m5FnT22JHNhN6CJYSol27sLa9m4LKCfbByQq9YodcNc59bTI9qaf5NMGaMTSQrvEj7Bto+oTXtmxzyyGHzgGQwbM8177YdaWTggY3EiawTPSf9Ap4KRop15uUwDz1z0e0nJsMjjn+GByyuE7vKIZAoWJ/MVkkjFqwlxPt2mr519Po5gONTlkLgRdYVnnQ8otLVzdRCCiX9cIDUFOb8cBtE76DvT+sciUvZ3uFRVWO7qgXGs2TnQjbbycR2LlOJV46XwX+wFfEC8d88SR8n7krdyUtFSIKvhgQ=
  file_glob: true
  file: "./frontend/build/distributions/tennis-frontend-*-SNAPSHOT.zip"
  overwrite: true
  skip_cleanup: true
  draft: true
  name: Latest
  tag_name: $TRAVIS_TAG
  body: Current development stage
  on:
    repo: thomasrepnik/tennisresv2
